# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

In [1]:
import pandas as pd
import numpy as np

### Exercício 1

In [13]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.

list1 = np.arange(1, 1000000, 1)
list2 = list(range(0, 1000000))

In [14]:
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
%time
print(type(list1))
list1 * 2

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 9.78 µs
<class 'numpy.ndarray'>


array([      2,       4,       6, ..., 1999994, 1999996, 1999998])

In [15]:
%time
print(type(list2))
list2 * 2

CPU times: user 9 µs, sys: 1 µs, total: 10 µs
Wall time: 18.6 µs
<class 'list'>


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [17]:
# Qual objeto oferece melhor performance, array NumPy ou lista?

Numpy oferece melhor performace

### Exercício 2

In [19]:
# Exercício 2
# Crie um array de 10 elementos
list = np.arange(1, 11, 1)
type(list)
print(list)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
list[5] = 0
list[8] = 0
print(list)

[ 1  2  3  4  5  0  7  8  0 10]


### Exercício 3

In [26]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
j = 3
k = 3 
l = 3

list = np.zeros((j, k, l))
type(list)
print(list[0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercício 4

In [37]:
# Crie um array de duas dimensões (matriz).
list = np.random.rand(4, 4)
print(list)

[[0.34993879 0.89800901 0.83983715 0.43308448]
 [0.56221387 0.40565135 0.7288209  0.2665576 ]
 [0.39493175 0.98979313 0.33034471 0.36353765]
 [0.06103412 0.44498286 0.04953756 0.79539626]]


In [38]:
# Imprima os elementos da terceira linha da matriz
print(list[2])

[0.06103412 0.44498286 0.04953756 0.79539626]


In [41]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
print(list[0:3])



[[0.34993879 0.89800901 0.83983715 0.43308448]
 [0.56221387 0.40565135 0.7288209  0.2665576 ]
 [0.39493175 0.98979313 0.33034471 0.36353765]]


### Exercício 5

In [43]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
print(arr.transpose())

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [48]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond.
# Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [49]:
for i in range(len(cond)):
    if cond[i] == True:
        print(xarr[i])
    else:
        print(yarr[i])


1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [62]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
list = np.arange(1, 11, 1)
print(list)
with open('test.npy', 'wb') as f:
    np.save(f, list)

[ 1  2  3  4  5  6  7  8  9 10]


In [63]:
# Depois carregue o array do disco no array B
with open('test.npy', 'rb') as f:
    gol = np.load(f)
    print(gol)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercício 8

In [64]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [66]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [103]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
import json
import io
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [109]:
df = resp.json()
df[0]['title']

'ENH: Change `MultiIndex.get_level_values()` to `MultiIndex.get_level()`'

In [112]:
data2 = pd.DataFrame(df, columns=['number', 'title',
                                    'labels', 'state'])
display(data2)

number                                              title  \
0    50497  ENH: Change `MultiIndex.get_level_values()` to...   
1    50496       DOC: MultiIndex methods not grouped together   
2    50495  BUG: `Series.isnull()` and `DataFrame.isnull()...   
3    50494                       DOC: Fix some doctest errors   
4    50493  CLN avoid some upcasting when its not the purp...   
5    50492  ENH: "one-to-one" validation in left join shou...   
6    50491                  ENH: Add lazy copy for sort_index   
7    50490  ENH: Add lazy copy for tz_convert and tz_localize   
8    50489                        TST: Test cow for set_flags   
9    50488  TST: GH50347 create test for groupby sum of bo...   
10   50487  DOC: IO tools OpenDocument spreadsheets har wr...   
11   50486  BUG: DataFrameGroupBy.value_counts fails with ...   
12   50483     DEPR: Remove unnecessary kwargs in groupby ops   
13   50482  BUG: SeriesGroupBy.value_counts sorts when sor...   
14   50481                DEP: Bump pytest, xdist, hypothesis   
15   50479      DEPR: Remove int64 uint64 float64 index tests   
16   50478                    ENH: Add lazy copy to swaplevel   
17   50477                    ENH: Add lazy copy for truncate   
18   50476       ENH: Add lazy copy for take and between_time   
19   50475            BUG: loc.setitem coercing rhs df dtypes   
20   50474            DOC: Add pyarrow type equivalency table   
21   50473                                              BUG:    
22   50472       ENH: Add lazy copy for series.reorder_levels   
23   50471     DOC: Add note about copy on write improvements   
24   50470                    DOC: Add Copy on write whatsnew   
25   50468       used regular expression in `format_is_iso()`   
26   50467  BUG: unwanted type conversion when partial rea...   
27   50465      PERF use regular expression in format_is_iso?   
28   50461  BUG: Order of dict items in DataFrame.from_dic...   
29   50460              TST: Verify mask's return keeps dtype   

                                               labels state  
0   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
1   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
4   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
5   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
6                                                  []  open  
7                                                  []  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
11  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
12  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
15                                                 []  open  
16                                                 []  open  
17                                                 []  open  
18                                                 []  open  
19  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
20  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22                                                 []  open  
23  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
24  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
25                                                 []  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27  [{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4ND...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open

### Exercício 10

In [17]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
import os
import sqlite3

# Criando conexao
con = sqlite3.connect('teste2.db')
# Criando o cursor
cur = con.cursor()

In [18]:
sql_create = 'create table Exemplo '\
'(id integer primary key, '\
'nome varchar(100), '\
'categoria varchar(140),'\
'valor intenger(99999))'

cur.execute(sql_create)


In [21]:
import numpy as np

recset = [(1000, 'Ciência de Dados', 'Data Science', ''),
          (1001, 'Big Data Fundamentos', 'Big Data','' ),
          (1002, 'Python Fundamentos', 'Análise de Dados','')]
sql_insert = 'insert into Exemplo values (?, ?, ?, ?)'
for rec in recset:
    cur.execute(sql_insert, rec)
con.commit()
con.close()

In [23]:
import pandas as pd

conn2 = sqlite3.connect("teste2.db")
tabelas = pd.read_sql_query("select * from Exemplo", conn2)
display(tabelas)

id                  nome         categoria valor
0  1000      Ciência de Dados      Data Science      
1  1001  Big Data Fundamentos          Big Data      
2  1002    Python Fundamentos  Análise de Dados

In [30]:
tabelas['valor'] = np.random.rand(3)
display(tabelas)

id                  nome         categoria     valor
0  1000      Ciência de Dados      Data Science  0.919147
1  1001  Big Data Fundamentos          Big Data  0.389130
2  1002    Python Fundamentos  Análise de Dados  0.815022

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
